# Generated by Django 3.2.4 on 2021-06-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('e', 'Electronica'), ('h', 'Hogar'), ('i', 'Indumentaria')], default='m', max_length=1),
        ),
    ]
