# Generated by Django 3.2.4 on 2021-06-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_auto_20210619_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='codigo',
        ),
    ]
