# Generated by Django 3.2.4 on 2021-06-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_alter_carrito_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
