# Generated by Django 3.2.4 on 2021-06-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.SmallIntegerField(choices=[(1, 'Electronica'), (2, 'Hogar'), (3, 'Indumentaria')], default=1),
        ),
    ]
